In [5]:

#1111
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.dtype

(tensor([[0.3164, 0.3560, 0.0563, 0.6868, 0.5204, 0.2001, 0.2517],
         [0.6665, 0.2032, 0.8788, 0.9705, 0.7072, 0.2986, 0.4758],
         [0.1222, 0.8173, 0.0835, 0.1290, 0.2250, 0.0706, 0.9109],
         [0.1243, 0.2728, 0.3292, 0.0940, 0.7945, 0.4762, 0.4285],
         [0.4563, 0.1334, 0.6018, 0.4384, 0.2285, 0.6115, 0.3834],
         [0.8319, 0.1004, 0.4309, 0.2455, 0.9718, 0.6910, 0.2295],
         [0.3385, 0.1894, 0.8331, 0.2601, 0.7977, 0.6918, 0.2037]]),
 torch.float32)

In [6]:
#22222

random_tensor = torch.rand(size=(7, 7))

other_tensor = torch.rand(size=(1, 7))

result = torch.matmul(random_tensor, other_tensor.T)

print(result)
print("Result shape:", result.shape)


tensor([[3.2893],
        [1.8615],
        [2.3932],
        [3.0200],
        [3.9279],
        [2.1280],
        [3.3274]])
Result shape: torch.Size([7, 1])


In [7]:
#3333
import torch


torch.manual_seed(0)

random_tensor = torch.rand(size=(7, 7))


other_tensor = torch.rand(size=(1, 7))

result = torch.matmul(random_tensor, other_tensor.T)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [8]:
#4444444
import torch

torch.manual_seed(0)

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)
    print("GPU seed set to 1234 ✅")
else:
    print("No GPU detected, seed set only for CPU ⚙️")


No GPU detected, seed set only for CPU ⚙️


In [11]:
#555555
import torch


torch.manual_seed(1234)


device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)


tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)


print(tensor1, tensor2)
#666666666
res = torch.matmul(tensor1,tensor2.T )
print(res,res.size())

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


In [12]:
#77777
max_val = torch.max(res)
min_val = torch.min(res)

print("Maximum value:", max_val)
print("Minimum value:", min_val)


Maximum value: tensor(0.5617)
Minimum value: tensor(0.3647)


In [13]:
#8888
max_index = torch.argmax(res)
min_index = torch.argmin(res)

print("Maximum index:", max_index)
print("Minimum index:", min_index)

Maximum index: tensor(3)
Minimum index: tensor(0)


In [15]:
#9999
torch.manual_seed(7)

t1 = torch.rand(1, 1, 1, 10)

t2 = t1.squeeze()

print(t1, t1.shape)
print(t2, t2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
